name: Docker image build with latest compiler version

on:
  push:
    branches: 
      - feature/*

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t gcc:latest -f Docker/Gcc/Dockerfile Docker

    services:
      dind:
        image: docker:19.03-dind
